create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

CREATE TABLE contact_persons
(
    id             bigint generated by default as identity,
    last_name       VARCHAR(255) NOT NULL,
    first_name      VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(15),
    company_id     BIGINT       NOT NULL,
    note           VARCHAR(255),
    status         VARCHAR(7)   NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    last_modified_at TIMESTAMP    NOT NULL,
    FOREIGN KEY (company_id) REFERENCES company (id)
);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

insert into contact_persons (last_name, first_name, email, phone_number, company_id, note, status, created_at,
                             last_modified_at)
values ('John', 'Doe', 'johndeo@gmail.com', '+36701234567', 1, 'great at listening', 'ACTIVE',
        '2021-06-22 19:10:25-07', '2021-06-22 19:10:25-07'),
       ('John', 'Smith', 'johnsmith@gmail.com', '+36208536458', 2, 'fast learner', 'ACTIVE',
        '2021-06-22 19:10:25-07', '2021-06-22 19:10:25-07'),
       ('Ana', 'Big', 'anabig@gmail.com', '+36707416892', 2, 'unreachable on mondays', 'ACTIVE',
        '2021-06-22 19:10:25-07', '2021-06-22 19:10:25-07');

